DEPTS = (
	('AFRI' , 'Africana Studies'),
	('AMST' , 'American Studies'),
	('ANTH' , 'Anthropology'),
	('ARHI' , 'Art History'),
	('ART' , 'Art'),
	('ASAM' , 'Asian American Studies'),
	('ASIA' , 'Asian Studies'),
	('ASTR' , 'Astronomy'),
	('BIOL' , 'Biology'),
	('CGSC' , 'Cognitive Science'),
	('CHEM' , 'Chemistry'),
	('CHIN' , 'Chinese'),
	('CHST' , 'Chicana/o-Latina/o Studies'),
	('CLAS' , 'Classics'),
	('CSCI' , 'Computer Science'),
	('DANC' , 'Dance'),
	('EA' , 'Environmental Analysis'),
	('ECON' , 'Economics'),
	('ENGL' , 'English'),
	('FREN' , 'French'),
	('GEOL' , 'Geology'),
	('GERM' , 'German Studies'),
	('GWS' , "Gender & Women's Studies"),
	('HIST' , 'History'),
	('IR' , 'International Relations'),
	('JAPN' , 'Japanese'),
	('LAMS' , 'Late Antique-Medieval Studies'),
	('LAST' , 'Latin American Studies'),
	('LG' , 'Linguistics'),
	('MATH' , 'Mathematics'),
	('MES' , 'Middle Eastern Studies'),
	('MOBI' , 'Molecular Biology'),
	('MS' , 'Media Studies'),
	('MUS' , 'Music'),
	('NEUR' , 'Neuroscience'),
	('PHIL' , 'Philosophy, Politics & Economics'),
	('PHYS' , 'Physics & Astronomy'),
	('POLI' , 'Politics'),
	('PPA' , 'Public Policy Analysis'),
	('PSYC' , 'Psychology'),
	('REST' , 'Russian & Eastern European Studies'),
	('RLIT' , 'Romance Languages & Literatures'),
	('RLST' , 'Religious Studies'),
	('RUSS' , 'Russian'),
	('SOC' , 'Sociology'),
	('SPAN' , 'Spanish'),
	('STS' , 'Science, Technology & Society'),
	('THEA' , 'Theatre'),
	)