# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017)),
                ('adv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.StudentProfile')),
            ],
        ),
    ]
