# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Cecil Sagehen', max_length=50)),
                ('dept', models.CharField(choices=[(b'AFRI', b'Africana Studies'), (b'AMST', b'American Studies'), (b'ANTH', b'Anthropology'), (b'ARHI', b'Art History'), (b'ART', b'Art'), (b'ASAM', b'Asian American Studies'), (b'ASIA', b'Asian Studies'), (b'ASTR', b'Astronomy'), (b'BIOL', b'Biology'), (b'CGSC', b'Cognitive Science'), (b'CHEM', b'Chemistry'), (b'CHIN', b'Chinese'), (b'CHST', b'Chicana/o-Latina/o Studies'), (b'CLAS', b'Classics'), (b'CSCI', b'Computer Science'), (b'DANC', b'Dance'), (b'EA', b'Environmental Analysis'), (b'ECON', b'Economics'), (b'ENGL', b'English'), (b'FREN', b'French'), (b'GEOL', b'Geology'), (b'GERM', b'German Studies'), (b'GWS', b"Gender & Women's Studies"), (b'HIST', b'History'), (b'IR', b'International Relations'), (b'JAPN', b'Japanese'), (b'LAMS', b'Late Antique-Medieval Studies'), (b'LAST', b'Latin American Studies'), (b'LG', b'Linguistics'), (b'MATH', b'Mathematics'), (b'MES', b'Middle Eastern Studies'), (b'MOBI', b'Molecular Biology'), (b'MS', b'Media Studies'), (b'MUS', b'Music'), (b'NEUR', b'Neuroscience'), (b'PHIL', b'Philosophy, Politics & Economics'), (b'PHYS', b'Physics & Astronomy'), (b'POLI', b'Politics'), (b'PPA', b'Public Policy Analysis'), (b'PSYC', b'Psychology'), (b'REST', b'Russian & Eastern European Studies'), (b'RLIT', b'Romance Languages & Literatures'), (b'RLST', b'Religious Studies'), (b'RUSS', b'Russian'), (b'SOC', b'Sociology'), (b'SPAN', b'Spanish'), (b'STS', b'Science, Technology & Society'), (b'THEA', b'Theatre')], default='CSCI', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
