# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=9)),
                ('area', models.CharField(choices=[('1', 'Area 1'), ('2', 'Area 2'), ('3', 'Area 3'), ('4', 'Area 4'), ('5', 'Area 5'), ('6', 'Area 6')], max_length=1, null=True)),
                ('overlay', models.CharField(choices=[('W', 'Writing Intensive'), ('WA', 'Writing Intesive/Analyzing Difference'), ('S', 'Speaking Intensive'), ('SA', 'Speaking Intensive/Analyzing Difference'), ('A', 'Analyzing Difference')], default=None, max_length=2, null=True)),
                ('credit', models.CharField(choices=[('Full', '1.0'), ('Half', '0.5'), ('Qrtr', '0.25')], max_length=4)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(default=2017)),
                ('semester', models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring')], max_length=2)),
                ('course', models.ManyToManyField(to='schedules.Course')),
            ],
            options={
                'ordering': ('term', 'semester'),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sem', models.CharField(max_length=4)),
                ('end_sem', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coursesession',
            unique_together=set([('term', 'semester')]),
        ),
    ]
