# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('1', 'Area 1'), ('2', 'Area 2'), ('3', 'Area 3'), ('4', 'Area 4'), ('5', 'Area 5'), ('6', 'Area 6')], max_length=1, null=True)),
                ('overlay', models.CharField(choices=[('W', 'Writing Intensive'), ('WA', 'Writing Intesive/Analyzing Difference'), ('S', 'Speaking Intensive'), ('SA', 'Speaking Intensive/Analyzing Difference'), ('A', 'Analyzing Difference')], max_length=2, null=True)),
                ('credit', models.CharField(choices=[('Full', '1.00'), ('Half', '0.50'), ('Qrtr', '0.25'), ('Zero', '0.00')], max_length=4)),
                ('link', models.URLField(blank=True, null=True)),
                ('pre_req', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(default=2017)),
                ('semester', models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring')], max_length=2)),
                ('courses', models.ManyToManyField(to='schedules.Course')),
            ],
            options={
                'ordering': ('term', 'semester'),
            },
        ),
        migrations.CreateModel(
            name='EquivCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_one', to='schedules.Course')),
                ('course_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_two', to='schedules.Course')),
                ('equiv_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiv_to', to='schedules.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sem', models.CharField(max_length=4)),
                ('end_sem', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('course_sessions', models.ManyToManyField(to='schedules.CourseSession')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.StudentProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='equivcourses',
            unique_together=set([('course_one', 'course_two', 'equiv_to')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursesession',
            unique_together=set([('term', 'semester')]),
        ),
    ]
