# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overlay',
            field=models.CharField(choices=[('W', 'Writing Intensive'), ('WA', 'Writing Intesive/Analyzing Difference'), ('S', 'Speaking Intensive'), ('SA', 'Speaking Intensive/Analyzing Difference'), ('A', 'Analyzing Difference')], max_length=2, null=True),
        ),
    ]
