# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=50),
        ),
    ]
