# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_scheduleoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_sem',
            field=models.CharField(choices=[(b'FA13', b'Fall 2013'), (b'SP14', b'Spring 2014'), (b'FA14', b'Fall 2014'), (b'SP15', b'Spring 2015'), (b'FA15', b'Fall 2015'), (b'SP16', b'Spring 2016'), (b'FA16', b'Fall 2016'), (b'SP17', b'Spring 2017'), (b'FA17', b'Fall 2017'), (b'SP18', b'Spring 2018'), (b'FA18', b'Fall 2018'), (b'SP19', b'Spring 2019'), (b'FA19', b'Fall 2019'), (b'SP20', b'Spring 2020'), (b'FA20', b'Fall 2020'), (b'SP21', b'Spring 2021')], max_length=4),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_sem',
            field=models.CharField(choices=[(b'FA13', b'Fall 2013'), (b'SP14', b'Spring 2014'), (b'FA14', b'Fall 2014'), (b'SP15', b'Spring 2015'), (b'FA15', b'Fall 2015'), (b'SP16', b'Spring 2016'), (b'FA16', b'Fall 2016'), (b'SP17', b'Spring 2017'), (b'FA17', b'Fall 2017'), (b'SP18', b'Spring 2018'), (b'FA18', b'Fall 2018'), (b'SP19', b'Spring 2019'), (b'FA19', b'Fall 2019'), (b'SP20', b'Spring 2020'), (b'FA20', b'Fall 2020'), (b'SP21', b'Spring 2021')], max_length=4),
        ),
    ]
