# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20170419_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleoptions',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='existing_credits',
            field=models.CharField(choices=[(b'ZERO', b'0'), (b'ONE', b'1'), (b'TWO', b'2')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='languages_completed',
            field=models.CharField(choices=[(b'ZERO', b'0'), (b'ONE', b'1'), (b'TWO', b'2'), (b'THREE', b'3')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='math_completed',
            field=models.CharField(choices=[(b'NONE', b'None'), (b'CALC1', b'Calc I'), (b'CALC2', b'Calc II'), (b'LINEAR', b'Linear+')], max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='ScheduleOptions',
        ),
    ]
