# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20170419_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
    ]
