# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_remove_course_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrereqCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='pre_req',
        ),
        migrations.AddField(
            model_name='prereqcourses',
            name='course_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_req', to='schedules.Course'),
        ),
        migrations.AddField(
            model_name='prereqcourses',
            name='course_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_take', to='schedules.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='prereqcourses',
            unique_together=set([('course_req', 'course_take')]),
        ),
    ]
